model = "dan"

[slurm]
qos = "gpu-medium"
time = "1-00:00:00"



[hyper]
"params.lr" = [0.001, 0.0001, 0.00001]
"params.dropout" = [0.2, 0.35, 0.5]
"params.hidden_dim" = [100, 300, 500, 1000]
"params.pool" = ["sum", "avg"]

[params]
dropout = 0.5
lr = 0.001
hidden_dim = 300
pool = "avg"

